### ISSUE TITLE
(Chrome) Doesn't download content

### ISSUE THREAD

**Issue by Neatro** [Flkalas/TwitterMediaAssist#23]
**(Chrome version)**

Doesn't download the image when clicking the download button under the tweet.

Error in console:

```
Uncaught ReferenceError: accumIndex is not defined
    at HTMLImageElement.<anonymous> (twitter_video_assist_client.js:185:76)
    at Function.each (jquery-3.3.1.min.js:2:2573)
    at w.fn.init.each (jquery-3.3.1.min.js:2:1240)
    at downloadImageObject (twitter_video_assist_client.js:176:15)
    at HTMLDivElement.downloadMediaObject (twitter_video_assist_client.js:142:9)
    at HTMLDivElement.dispatch (jquery-3.3.1.min.js:2:41772)
    at y.handle (jquery-3.3.1.min.js:2:39791)
```

**Comment by Flkalas** [comment]
How about 3.1 version? I would fix in this version.

**Comment by Neatro** [comment]
Works again on version 3.1, thank you!
